### ISSUE TITLE
Add switch for SourceTree please :)

### ISSUE THREAD

**Issue by rawaludin** [mermaid/alfred-dark-mode-toggle#1]
Hey, thanks for the workflow. I'm not really understand how the script work. Could you add switch for sourcetree app too?

<img width="792" alt="screen shot 2018-09-29 at 07 57 29" src="https://user-images.githubusercontent.com/1274849/46239072-a50b0c00-c3bd-11e8-9069-06c7978ef16e.png">

**Comment by mermaid** [comment]
I added native sourcetree support. You can enable it by downloading the new version, editing the workflow, and connecting the `Toggle MacOS Dark Mode` section to the `SourceTree` section.

**Comment by rawaludin** [comment]
Thanks!
