### ISSUE TITLE
Searching "dark" and "light"

### ISSUE THREAD

**Issue by jackfirth** [mermaid/alfred-dark-mode-toggle#4]
I love this thing. Small UX issue though: I usually don't think "change to the other theme", I think "change to dark" or "change to light". So when I open Alfred I search "dark" or "light" before remembering I need to search "theme" to get the the list items to show up. Can this workflow be updated so that in addition to searching "theme" listing the toggle/dark/light options, searching "dark" lists just the switch-to-dark option and searching "light" lists just the switch-to-light option?

**Comment by mermaid** [comment]
That is definitely a better UX than what it was.
I've updated it so that you can search for light/dark as well
